name: C/C++ CI

on:
  push:
    branches:
      - dev_server
      - test_actions
      - master
    pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: make -C server/
        run: make -C server/
      - name: make clean
        run: make clean -C server/
      - name: make fclean -C server/
        run: make -C server/ ; make fclean -C server/
      - name: make re -C server/
        run: make re -C server/
  update_remote:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: clone
        run: git clone git@github.com:/Emilien-Delevoye/PSU_zappy_2019
      - name: add remote
        run: cd PSU_zappy_2019 ; git remote add blih git@git.epitech.eu:/emilien.delevoye@epitech.eu/PSU_zappy_2019
      - name: push
        run: cd PSU_zappy_2019 ; git push blih
  unit_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: make tests_run
      - name: Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          token: 01f9eabc-56f3-4979-8928-620f507b0fb6

